/*
 * Ksyxis is a third-party mod for Minecraft Java Edition that
 * speed ups your world loading by removing unneeded chunks.
 *
 * MIT License
 *
 * Copyright (c) 2021-2026 VidTu
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * SPDX-License-Identifier: MIT
 */

package ru.vidtu.ksyxis;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.Marker;
import org.apache.logging.log4j.MarkerManager;
import org.jetbrains.annotations.ApiStatus;
import org.jetbrains.annotations.Contract;
import org.jspecify.annotations.NullMarked;
import org.spongepowered.asm.launch.MixinBootstrap;
import org.spongepowered.asm.mixin.Mixins;
import ru.vidtu.ksyxis.platform.KCompile;
import ru.vidtu.ksyxis.platform.KPlugin;

import java.lang.reflect.Field;

/**
 * Main Ksyxis class.
 *
 * @author VidTu
 * @apiNote Internal use only
 * @see KPlugin
 */
@ApiStatus.Internal
@NullMarked
public final class Ksyxis {
    /**
     * Marker for all logs generated by the mod.
     */
    public static final Marker KSYXIS_MARKER = MarkerManager.getMarker("MOD_KSYXIS");

    /**
     * Logger for this class.
     */
    private static final Logger LOGGER = LogManager.getLogger("Ksyxis");

    /**
     * An instance of this class cannot be created.
     *
     * @throws AssertionError Always
     * @deprecated Always throws
     */
    @ApiStatus.ScheduledForRemoval
    @Deprecated
    @Contract(value = "-> fail", pure = true)
    private Ksyxis() {
        throw new AssertionError("Ksyxis: No instances.");
    }

    /**
     * Initializes the mod. If {@code manual}, bootstraps the Mixin and injects its configuration.
     *
     * @param platform Current platform
     * @param manual   Whether to bootstrap the Mixin inject Mixin configuration manually
     * @see MixinBootstrap#init()
     * @see Mixins#addConfiguration(String)
     */
    public static void init(final String platform, final boolean manual) {
        try {
            // Validate.
            if (KCompile.DEBUG_ASSERTS) {
                assert (platform != null) : "Ksyxis: Parameter 'platform' is null. (manual: " + manual + ')';
            }

            // Log.
            final long start = System.nanoTime();
            LOGGER.info(KSYXIS_MARKER, "Ksyxis: Loading... (platform: {}, version: " + KCompile.VERSION + ", manual: {})", new Object[]{platform, manual}); // <- Array for compat with older Log4j2.

            // Get the Mixin version field.
            final Field mixinVersionField = MixinBootstrap.class.getField("VERSION");

            // Get the Mixin version field value without javac constant inlining.
            final String mixinVersion = (String) mixinVersionField.get(null);

            // Log. (**DEBUG**)
            if (KCompile.DEBUG_LOGS && LOGGER.isDebugEnabled(KSYXIS_MARKER)) {
                LOGGER.debug(KSYXIS_MARKER, "Ksyxis: Found Mixin library. (mixinVersion: {})", new Object[]{mixinVersion}); // <- Array for compat with older Log4j2.
            }

            // Do manual Mixin injections, if enabled.
            if (manual) {
                // Log. (**DEBUG**)
                if (KCompile.DEBUG_LOGS) {
                    LOGGER.debug(KSYXIS_MARKER, "Ksyxis: Bootstrapping Mixin...");
                }

                // Bootstrap Mixin.
                MixinBootstrap.init();

                // Log. (**DEBUG**)
                if (KCompile.DEBUG_LOGS) {
                    LOGGER.debug(KSYXIS_MARKER, "Ksyxis: Mixin bootstrapped. Adding the config...");
                }

                // Add the config.
                Mixins.addConfiguration("ksyxis.mixins.json");

                // Log. (**DEBUG**)
                if (KCompile.DEBUG_LOGS) {
                    LOGGER.debug(KSYXIS_MARKER, "Ksyxis: Mixin config added.");
                }
            }

            // Log the info.
            LOGGER.info(KSYXIS_MARKER, "Ksyxis: Ready to remove unneeded chunks. (mixinVersion: {}, time: {} ms)", new Object[]{mixinVersion, (System.nanoTime() - start) / 1_000_000L}); // <- Array for compat with older Log4j2.
        } catch (final Throwable t) {
            // Check if Mixin is absent.
            if ((t.getClass() == NoClassDefFoundError.class) && "org/spongepowered/asm/launch/MixinBootstrap".equals(t.getMessage())) {
                throw new RuntimeException("Ksyxis: No Mixin found.", t);
            }

            // Rethrow.
            throw new RuntimeException("Ksyxis: Unexpected init error.", t);
        }
    }
}
