/*
 * Ksyxis is a third-party mod for Minecraft Java Edition that
 * speed ups your world loading by removing unneeded chunks.
 *
 * MIT License
 *
 * Copyright (c) 2021-2026 VidTu
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * SPDX-License-Identifier: MIT
 */

package ru.vidtu.ksyxis.platform;

import com.google.errorprone.annotations.DoNotCall;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.Marker;
import org.apache.logging.log4j.MarkerManager;
import org.jetbrains.annotations.ApiStatus;
import org.jetbrains.annotations.CheckReturnValue;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.UnknownNullability;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.tree.ClassNode;
import org.spongepowered.asm.mixin.extensibility.IMixinConfigPlugin;
import org.spongepowered.asm.mixin.extensibility.IMixinInfo;
import org.spongepowered.asm.service.IClassBytecodeProvider;
import org.spongepowered.asm.service.MixinService;

import java.util.List;
import java.util.Set;

/**
 * Mixin plugin that silences the console {@link ClassNotFoundException} errors from Ksyxis.
 *
 * @author VidTu
 * @apiNote Internal use only
 */
@ApiStatus.Internal
@NullMarked
public final class KPlugin implements IMixinConfigPlugin {
    /**
     * Marker for all logs generated by the mod.
     */
    @UnknownNullability
    public static final Marker MARKER = (KCompile.DEBUG_LOGS ? MarkerManager.getMarker("MOD_KSYXIS") : null);

    /**
     * Logger for this class.
     */
    @UnknownNullability
    private static final Logger LOGGER = (KCompile.DEBUG_LOGS ? LogManager.getLogger("Ksyxis/KPlugin") : null);

    /**
     * Current Mixin bytecode provider.
     */
    private final IClassBytecodeProvider provider = MixinService.getService().getBytecodeProvider();

    /**
     * Whether the code data should be skipped in {@link ClassReader} when checking the class data. {@code true}
     * is used whenever possible for performance, {@code false} is used if not yet supported by current provider.
     */
    private final boolean skipCode = (IClassBytecodeProvider.class.getMethods().length >= 3);

    /**
     * Whether the transformers should be run when checking the class data. {@code false} is used whenever possible
     * for performance, {@code true} is used if current bytecode provider doesn't support untransformed classes.
     */
    private final boolean runTransformers;

    /**
     * Creates a new plugin.
     *
     * @apiNote Do not call, called by Mixin
     */
    @Contract(pure = true)
    public KPlugin() {
        // Determine the transformers.
        final String providerClass = this.provider.getClass().getName();
        this.runTransformers = ("org.spongepowered.asm.launch.MixinLaunchPluginLegacy".equals(providerClass) ||
                "org.spongepowered.asm.launch.MixinLaunchPlugin".equals(providerClass));
    }

    /**
     * Checks if the mixin should be applied. A mixin is applied, if its class node exists. The existence of
     * the class node is checked via {@link IClassBytecodeProvider#getClassNode(String)} from {@link #provider}.
     *
     * @param targetClassName Fully qualified class name of the target class
     * @param mixinClassName  Fully qualified class name of the mixin
     * @return Whether the Mixin should be applied
     * @apiNote Do not call, called by Mixin
     * @see #provider
     * @see IClassBytecodeProvider#getClassNode(String)
     */
    @DoNotCall("Called by Mixin")
    @CheckReturnValue
    @Override
    public boolean shouldApplyMixin(final String targetClassName, final String mixinClassName) {
        // Wrap to handle exceptions as a control flow.
        try {
            // Validate.
            if (KCompile.DEBUG_ASSERTS) {
                assert (targetClassName != null) : "Ksyxis: Parameter 'targetClassName' is null. (mixinClassName: " + mixinClassName + ", plugin: " + this + ')';
                assert (mixinClassName != null) : "Ksyxis: Parameter 'mixinClassName' is null. (targetClassName: " + targetClassName + ", plugin: " + this + ')';
            }

            // If the Mixin class is not from Ksyxis, don't touch it and allow it to be applied.
            if (!mixinClassName.startsWith("ru.vidtu.ksyxis.mixin.")) { // Implicit NPE for 'mixinClassName'
                // Log. (**TRACE**)
                if (KCompile.DEBUG_LOGS && LOGGER.isTraceEnabled(MARKER)) {
                    LOGGER.trace(MARKER, "Ksyxis: Skipping and applying mixin, because it's not a part of Ksyxis... (targetClassName: {}, mixinClassName: {}, plugin: {})", new Object[]{targetClassName, mixinClassName, this}); // <- Array for compat with older Log4j2.
                }

                // Unconditionally apply.
                return true;
            }

            // Get the node:
            // - It returns the class node, if the class exists.
            // - It throws ClassNotFoundException if the class doesn't exist.
            if (this.skipCode) {
                this.provider.getClassNode(targetClassName, this.runTransformers, ClassReader.SKIP_CODE | ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES); // Implicit NPE for 'targetClassName'
            } else {
                this.provider.getClassNode(targetClassName, this.runTransformers); // Implicit NPE for 'targetClassName'
            }

            // Log. (**DEBUG**)
            if (KCompile.DEBUG_LOGS && LOGGER.isDebugEnabled(MARKER)) {
                LOGGER.debug(MARKER, "Ksyxis: Bytecode provider returned a valid node, mixin WILL be applied. (targetClassName: {}, mixinClassName: {}, plugin: {})", new Object[]{targetClassName, mixinClassName, this}); // <- Array for compat with older Log4j2.
            }

            // Didn't throw - class exists.
            return true;
        } catch (final ClassNotFoundException cnfe) {
            // Log. (**DEBUG**)
            if (KCompile.DEBUG_LOGS && LOGGER.isDebugEnabled(MARKER)) {
                LOGGER.debug(MARKER, "Ksyxis: Bytecode provider threw an CNFE, mixin WON'T be applied. (targetClassName: {}, mixinClassName: {}, plugin: {})", new Object[]{targetClassName, mixinClassName, this, cnfe}); // <- Array for compat with older Log4j2.
            }

            // Provider threw an ClassNotFoundException. Don't apply mixin to avoid warnings. 
            return false;
        } catch (final Throwable t) {
            // Rethrow.
            throw new RuntimeException("Ksyxis: Unexpected plugin error. (targetClassName: " + targetClassName + ", mixinClassName: " + mixinClassName + ", plugin: " + this + ')', t);
        }
    }

    /**
     * Does nothing.
     *
     * @param mixinPackage Ignored
     * @apiNote Do not call, called by Mixin
     */
    @DoNotCall("Called by Mixin")
    @Contract(pure = true)
    @Override
    public void onLoad(final String mixinPackage) {
        // Validate.
        if (KCompile.DEBUG_ASSERTS) {
            assert (mixinPackage != null) : "Ksyxis: Parameter 'mixinPackage' is null. (plugin: " + this + ')';
        }

        // NO-OP
    }

    /**
     * Does nothing. Always returns {@code null}.
     *
     * @return Always {@code null}
     * @apiNote Do not call, called by Mixin
     */
    @DoNotCall("Called by Mixin")
    @Contract(value = "-> null", pure = true)
    @Override
    @Nullable
    public String getRefMapperConfig() {
        return null;
    }

    /**
     * Does nothing.
     *
     * @param myTargets    Ignored
     * @param otherTargets Ignored
     * @apiNote Do not call, called by Mixin
     */
    @DoNotCall("Called by Mixin")
    @Contract(pure = true)
    @Override
    public void acceptTargets(final Set<String> myTargets, final Set<String> otherTargets) {
        // Validate.
        if (KCompile.DEBUG_ASSERTS) {
            assert (myTargets != null) : "Ksyxis: Parameter 'myTargets' is null. (otherTargets: " + otherTargets + ", plugin: " + this + ')';
            assert (otherTargets != null) : "Ksyxis: Parameter 'otherTargets' is null. (myTargets: " + myTargets + ", plugin: " + this + ')';
        }

        // NO-OP
    }

    /**
     * Does nothing. Always returns {@code null}.
     *
     * @return Always {@code null}
     * @apiNote Do not call, called by Mixin
     */
    @DoNotCall("Called by Mixin")
    @Contract(value = "-> null", pure = true)
    @Override
    @Nullable
    public List<String> getMixins() {
        return null;
    }

    /**
     * Does nothing.
     *
     * @param targetClassName Ignored
     * @param targetClass     Ignored
     * @param mixinClassName  Ignored
     * @param mixinInfo       Ignored
     * @apiNote Do not call, called by Mixin
     */
    @DoNotCall("Called by Mixin")
    @Contract(pure = true)
    @Override
    public void preApply(final String targetClassName, final ClassNode targetClass,
                         final String mixinClassName, final IMixinInfo mixinInfo) {
        // Validate.
        if (KCompile.DEBUG_ASSERTS) {
            assert (targetClassName != null) : "Ksyxis: Parameter 'targetClassName' is null. (targetClass: " + targetClass + ", mixinClassName: " + mixinClassName + ", mixinInfo: " + mixinInfo + ", plugin: " + this + ')';
            assert (targetClass != null) : "Ksyxis: Parameter 'targetClass' is null. (targetClassName: " + targetClassName + ", mixinClassName: " + mixinClassName + ", mixinInfo: " + mixinInfo + ", plugin: " + this + ')';
            assert (mixinClassName != null) : "Ksyxis: Parameter 'mixinClassName' is null. (targetClassName: " + targetClassName + ", targetClass: " + targetClass + ", mixinInfo: " + mixinInfo + ", plugin: " + this + ')';
            assert (mixinInfo != null) : "Ksyxis: Parameter 'mixinInfo' is null. (targetClassName: " + targetClassName + ", targetClass: " + targetClass + ", mixinClassName: " + mixinClassName + ", plugin: " + this + ')';
        }

        // NO-OP
    }

    /**
     * Does nothing.
     *
     * @param targetClassName Ignored
     * @param targetClass     Ignored
     * @param mixinClassName  Ignored
     * @param mixinInfo       Ignored
     * @apiNote Do not call, called by Mixin
     */
    @DoNotCall("Called by Mixin")
    @Contract(pure = true)
    @Override
    public void postApply(final String targetClassName, final ClassNode targetClass,
                          final String mixinClassName, final IMixinInfo mixinInfo) {
        // Validate.
        if (KCompile.DEBUG_ASSERTS) {
            assert (targetClassName != null) : "Ksyxis: Parameter 'targetClassName' is null. (targetClass: " + targetClass + ", mixinClassName: " + mixinClassName + ", mixinInfo: " + mixinInfo + ", plugin: " + this + ')';
            assert (targetClass != null) : "Ksyxis: Parameter 'targetClass' is null. (targetClassName: " + targetClassName + ", mixinClassName: " + mixinClassName + ", mixinInfo: " + mixinInfo + ", plugin: " + this + ')';
            assert (mixinClassName != null) : "Ksyxis: Parameter 'mixinClassName' is null. (targetClassName: " + targetClassName + ", targetClass: " + targetClass + ", mixinInfo: " + mixinInfo + ", plugin: " + this + ')';
            assert (mixinInfo != null) : "Ksyxis: Parameter 'mixinInfo' is null. (targetClassName: " + targetClassName + ", targetClass: " + targetClass + ", mixinClassName: " + mixinClassName + ", plugin: " + this + ')';
        }

        // NO-OP
    }

    @Contract(pure = true)
    @Override
    public String toString() {
        return "Ksyxis/KPlugin{" +
                "provider=" + this.provider +
                ", skipCode=" + this.skipCode +
                ", runTransformers=" + this.runTransformers +
                '}';
    }
}
