modLoader = "javafml"
loaderVersion = "*"
license = "MIT"
issueTrackerURL = "https://github.com/VidTu/Ksyxis/issues"

[[mods]]
modId = "ksyxis"
version = "${version}"
displayName = "Ksyxis"
updateJSONURL = "https://raw.githubusercontent.com/VidTu/Ksyxis/main/updater_ksyxis_forge.json"
displayURL = "https://modrinth.com/mod/ksyxis"
issueTrackerURL = "https://github.com/VidTu/Ksyxis/issues"
catalogueImageIcon = "ksyxis_64.png"
catalogueItemIcon = "minecraft:porkchop"
catalogueBackground = "ksyxis_background.png"
itemIcon = "minecraft:porkchop"
logoFile = "ksyxis_240.png"
authors = "VidTu"
displayTest = "IGNORE_ALL_VERSION"
description = '''Speed up your world loading by removing spawn chunks.'''

[[mixins]]
config = "ksyxis.mixins.json"

[modproperties.ksyxis]
catalogueImageIcon = "ksyxis_64.png"
catalogueItemIcon = "minecraft:porkchop"
catalogueBackground = "ksyxis_background.png"
itemIcon = "minecraft:porkchop"
logoFile = "ksyxis_240.png"
