# Ksyxis is a third-party mod for Minecraft Java Edition that
# speed ups your world loading by removing spawn chunks.
#
# MIT License
#
# Copyright (c) 2021-2026 VidTu
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# SPDX-License-Identifier: MIT

# Java:
# - Target: 25.0.2, released January 2026.
# - Update: February 2nd, 2026. (UTC)
# Vendors:
# - Eclipse Temurin: FreeBSD, Linux, UNIX, Windows (x86_64).
# - Azul Zulu: Windows (arm64).

toolchainUrl.FREE_BSD.AARCH64=https:\//api.adoptium.net/v3/binary/version/jdk-25.0.2+10/linux/aarch64/jdk/hotspot/normal/eclipse
toolchainUrl.FREE_BSD.X86_64=https\://api.adoptium.net/v3/binary/version/jdk-25.0.2+10/linux/x64/jdk/hotspot/normal/eclipse
toolchainUrl.LINUX.AARCH64=https:\//api.adoptium.net/v3/binary/version/jdk-25.0.2+10/linux/aarch64/jdk/hotspot/normal/eclipse
toolchainUrl.LINUX.X86_64=https\://api.adoptium.net/v3/binary/version/jdk-25.0.2+10/linux/x64/jdk/hotspot/normal/eclipse
toolchainUrl.MAC_OS.AARCH64=https\://api.adoptium.net/v3/binary/version/jdk-25.0.2+10/mac/aarch64/jdk/hotspot/normal/eclipse
toolchainUrl.MAC_OS.X86_64=https\://api.adoptium.net/v3/binary/version/jdk-25.0.2+10/mac/x64/jdk/hotspot/normal/eclipse
toolchainUrl.UNIX.AARCH64=https:\//api.adoptium.net/v3/binary/version/jdk-25.0.2+10/linux/aarch64/jdk/hotspot/normal/eclipse
toolchainUrl.UNIX.X86_64=https\://api.adoptium.net/v3/binary/version/jdk-25.0.2+10/linux/x64/jdk/hotspot/normal/eclipse
toolchainUrl.WINDOWS.AARCH64=https\://cdn.azul.com/zulu/bin/zulu25.32.21-ca-jdk25.0.2-win_aarch64.zip
toolchainUrl.WINDOWS.X86_64=https\://api.adoptium.net/v3/binary/version/jdk-25.0.2+10/windows/x64/jdk/hotspot/normal/eclipse
toolchainVersion=25
