[versions]
asm = "9.7"
log4j = "2.23.1"
mixin = "0.8.7"

[libraries]
asm = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
log4j = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
