name: Feature request
description: Suggest an improvement for this mod
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: "Related problem"
      description: "A clear and concise description of what the problem is."
      placeholder: "I'm always frustrated when..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
      placeholder: "An option to make..."
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Also I'd like to..."
    validations:
      required: false
